source 'https://rubygems.org'

gem 'appium_console'
gem 'appium_lib',         '~> 4.1.0'
gem 'rest-client',        '~> 1.7.1'
gem 'rspec',              '~> 2.14.1'
gem 'rspec-expectations', '~> 2.14.5'
gem 'spec',               '~> 5.3.4'
gem 'sauce_whisk',        '~> 0.0.14'
gem 'test-unit',          '~> 2.5.5'
gem 'byebug'
gem 'faker'